/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.mochgani.crudoop.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author MochGani
 */
public class FrmMain extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        
        this.setSize(xsize, ysize);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAkses = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSiswa = new javax.swing.JMenu();
        mnPeminjaman = new javax.swing.JMenu();
        mnUser = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblName.setText("jLabel1");

        jLabel1.setText("Nama Petugas");

        jLabel2.setText("Akses");

        lblAkses.setText("jLabel3");

        mnSiswa.setText("Siswa");
        mnSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSiswaMouseClicked(evt);
            }
        });
        mnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSiswaActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnSiswa);

        mnPeminjaman.setText("Peminjaman Buku");
        jMenuBar1.add(mnPeminjaman);

        mnUser.setText("User");
        mnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnUserMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnUser);

        mnLogout.setText("Logout");
        mnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAkses)
                    .addComponent(lblName))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAkses))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSiswaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnSiswaActionPerformed

    private void mnSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSiswaMouseClicked
        // TODO add your handling code here:
        FrmSiswa fs = new FrmSiswa();
        
        fs.setAlwaysOnTop(true);
        fs.setVisible(true);
    }//GEN-LAST:event_mnSiswaMouseClicked

    private void mnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnLogoutMouseClicked
        // TODO add your handling code here:
        FrmLogin fl = new FrmLogin();
        
        dispose();
        fl.setVisible(true);
    }//GEN-LAST:event_mnLogoutMouseClicked

    private void mnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnUserMouseClicked
        // TODO add your handling code here:
        FrmUser fu = new FrmUser();
        
        fu.setAlwaysOnTop(true);
        fu.setVisible(true);
    }//GEN-LAST:event_mnUserMouseClicked

    public void setName(String name) {
        lblName.setText(name);
    }
    
    public void setAkses(String akses) {
        lblAkses.setText(akses);
        
        if(akses.equals("USER")){
            mnPeminjaman.setVisible(false);
            mnUser.setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAkses;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenu mnLogout;
    private javax.swing.JMenu mnPeminjaman;
    private javax.swing.JMenu mnSiswa;
    private javax.swing.JMenu mnUser;
    // End of variables declaration//GEN-END:variables
}
